### ISSUE TITLE
Logout returns Error 405 

### ISSUE THREAD

**Issue by drewskoots** [jk-ethz/franka_lock_unlock#2]
My Franka panda is running system 4.1.1, and while logout seems to work or not really be neccessary, the assertion fails and throws the error that logout failed.

**Comment by jk-ethz** [comment]
Logout is just nice to have such that the session token gets released in the Panda control box.

Could you show the log output that it prints when the assertion fails.
It is fine to comment out this assertion if it causes problems for you.

**Comment by jk-ethz** [comment]
Also thanks for porting to ROS2. Feel free to open a PR in case it is possible to still work on ROS1.

**Comment by drewskoots** [comment]
This is the output I get upon quitting the program:
```
KeyboardInterrupt
Cleaning up...
Logging in...
Already logged in.
Requesting a control token...
Already having a control token.
Successfully acquired control over the robot.
Locking the robot...
Successfully locked the robot.
Releasing control token...
Successfully released control token.
Logging out...
405
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "src/franka_lock_unlock/franka_lock_unlock/__init__.py", line 48, in _cleanup
    self.run(unlock=False)
  File "src/franka_lock_unlock/franka_lock_unlock/__init__.py", line 221, in run
    self._logout()
  File "src/franka_lock_unlock/franka_lock_unlock/__init__.py", line 89, in _logout
    assert logout.status_code == 200, "Error logging out"
AssertionError: Error logging out
```
the error doesn't seem to be causing any issues, so I've just commented out the assertion as you suggested. 

Regarding my ROS2 port, unfortunately I think the launch files are incompatible, as are a few other things that I'm not thinking of right now. Maybe one could make 2 branches out of it instead?

**Comment by jk-ethz** [comment]
Ok, seems like there is an incompatible break of the API in the version of Franka Desk you are using. Updating to 4.2.1 would likely fix it.

If you need 4.1.1 want me to have a look and have Firefox installed, you could log into Desk. Then, just before logging out, press CTRL+SHIFT+I and go to "Network analysis". Then, log out of Desk and afterwards click on the right top settings wheel in the inspection panel and "Save all as HAR". Then, upload the HAR file here.
But I think it is fine without logout as well.

Yes, alternative branch would be possible, but changes or improvements would need to be transferred back-and-forth.

**Comment by drewskoots** [comment]
I think its fine as it is with the commented out assertion. You also raise a good point with the branches. I guess I'll just keep the fork separate and just merge your __init__.py edits as they happen. That's the main thing that will change I imagine.
